# =============================================
# Perfil DOCKER - Producción con Contenedores
# =============================================
# Usa PostgreSQL Master para escritura
# Usa PostgreSQL Replica para lectura
# =============================================

spring:
  config:
    activate:
      on-profile: docker

  # =============================================
  # Configuración CQRS - DataSources
  # =============================================
  datasource:
    # DataSource de escritura (Master)
    write:
      url: jdbc:postgresql://postgres-master:5432/ecommerce
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: WriteHikariPool
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    # DataSource de lectura (Replica)
    read:
      url: jdbc:postgresql://postgres-replica:5433/ecommerce
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: ReadHikariPool
        maximum-pool-size: 20
        minimum-idle: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

auth:
  email:
    url: http://frontend:3000

logging:
  level:
    org.hibernate.SQL: OFF
